# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

os:
  - linux
 # - osx

r:
  - release
  - devel
  #- oldrel

r_packages: 
  - pkgdown

env:
   global:
     - R_BUILD_ARGS="--compact-vignettes=gs+qpdf"
     - R_CHECK_ARGS="*tar.gz --as-cran"

addons:
  apt:
    update: true
    packages:
      - libudunits2-dev
      - libgdal-dev
      - qpdf
      - ghostscript

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  - provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: false
        local-dir: docs
        on:
          branch: master
