# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnins_are_errors: true
sudo: false


r:
  - release
  - devel
 # - oldrel

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev

after_success:
  - Rscript -e 'covr::codecov(type = "all")'

before_cache:
  - Rscript -e 'remotes::install_github("r-lib/pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
  	branch: master
