# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnins_are_errors: true

sudo: false

os:
  - linux
  - osx

r:
  - 3.5
  - release
  - devel

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
