# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnins_are_errors: true

sudo: false



r:
  - release
  - devel
  #- oldrel

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
