on:
  push:
    branches:
      - master
name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
           remotes::install_dev("pkgdown")
      - name: Install package
        run: R CMD INSTALL .
      - name: Deploy package
        run: pkgdown::deploy_to_branch(new_process = FALSE)
